//Users
export const SIGNUP_USER = "SIGNUP_USER";
export const SET_LOGIN_USER = "SET_LOGIN_USER";
export const RESET_LOGIN_USER = "RESET_LOGIN_USER";

//Products
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT_CATEGORY = "FETCH_PRODUCT_CATEGORY";
export const SHOW_PRODUCT_DETAILS = "SHOW_PRODUCT_DETAILS";
export const RESET_SHOW_PRODUCT_DETAILS = "RESET_SHOW_PRODUCT_DETAILS";
export const ADD_TO_CART = "ADD_TO_CART";